//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabincrew.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Crew_dutyfree
    {
        [Key]
        //[DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int id { get; set; }
        public int flightid { get; set; }
        public string crewid { get; set; }
        public string mainbase { get; set; }
        public string month { get; set; }
        public Nullable<double> commission { get; set; }
        public Nullable<int> rate { get; set; }
        public string note { get; set; }
    }
}
