//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabincrew.Model.HR
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("danhmuc")]
    public partial class danhmuc
    {
        public int id { get; set; }
        public string MaDanhMuc { get; set; }
        public string TenDanhMuc { get; set; }
        public string LoaiDanhMuc { get; set; }
        public bool TinhTrang { get; set; }
        public Nullable<int> idDanhMucCu { get; set; }
        public string nhom { get; set; }
    }
}
