//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabincrew.Model.CCSK
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Healthcare
    {
        public int ID { get; set; }
        public string Code_tv { get; set; }
        public Nullable<System.DateTime> Dotkham { get; set; }
        public Nullable<System.DateTime> Expired { get; set; }
        
    }
}
