//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabincrew.Model.ERMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERMSEntities1 : DbContext
    {
        public ERMSEntities1()
            : base("name=ERMSEntities1")
        {
        }
          
        public DbSet<CR_Flight_Dutyfree> CR_Flight_Dutyfree { get; set; }
        public DbSet<CR_FlightInfo> CR_FlightInfo { get; set; }
        public DbSet<CR_Flight_Crew> CR_Flight_Crew { get; set; }
    }
}
